version: '3.9'

services:

  db:
    image: postgres:16
    container_name: crypto_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_reconciliation

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: crypto_backend

    restart: always

    ports:
      - "8000:8000"

    depends_on:
      - db

    env_file:
      - .env

volumes:
  postgres_data:
